# Generated by Django 3.0.6 on 2020-05-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=128, unique=True, verbose_name='GID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=128, unique=True, verbose_name='GID')),
                ('name', models.CharField(max_length=512, verbose_name='Название проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=128, unique=True, verbose_name='GID')),
                ('name', models.CharField(max_length=512, verbose_name='Название задачи')),
                ('notes', models.TextField(max_length=3000, verbose_name='Текст задачи')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.AsanaUser', verbose_name='Исполнитель')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to='core.AsanaUser', verbose_name='Закончил')),
                ('projects', models.ManyToManyField(related_name='tasks', to='core.Project', verbose_name='Проекта')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
