# Generated by Django 3.0.6 on 2020-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asanauser',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизировано'),
        ),
        migrations.AddField(
            model_name='project',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизировано'),
        ),
        migrations.AddField(
            model_name='task',
            name='synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизировано'),
        ),
        migrations.AlterField(
            model_name='asanauser',
            name='gid',
            field=models.CharField(editable=False, max_length=128, null=True, unique=True, verbose_name='GID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gid',
            field=models.CharField(editable=False, max_length=128, null=True, unique=True, verbose_name='GID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='gid',
            field=models.CharField(editable=False, max_length=128, null=True, unique=True, verbose_name='GID'),
        ),
    ]
